on:
  push:
    paths:
      - .github/workflows/**
      - "**.py"
      - "**.sh"
  pull_request:
    paths:
      - .github/workflows/**
      - "**.py"
      - "**.sh"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        run: |
          sudo apt install -y shellcheck
          shellcheck *.sh

      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install dev dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.dev.txt

      - name: setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: flake8
        run: python -m flake8

      - name: mypy
        run: python -m mypy
